SELECT b.B_SEQ AS B_SEQ, TITLE , b.B_WRITER  , B_CONTENT , B_REGDATE , B_DELFLAG , R_SEQ , R_WRITER , R_CONTENT , R_REGDATE , R_DELFLAG , F_SEQ , ORIGIN_FNAME 
			FROM BOARD b LEFT JOIN REPLY r 
			ON b.B_SEQ = r.B_SEQ
			LEFT JOIN FILEFILE f 
			ON b.B_SEQ = f.B_SEQ 
			WHERE f.B_SEQ = 1;