CREATE TABLE ROOTBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(100) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE	
);
SELECT MAX(SEQ) AS SEQ FROM ROOTBOARD;
CREATE TABLE REPLYBOARD(
	SEQ CHAR(3) PRIMARY KEY,
	"REF" NUMBER,
	TITLE VARCHAR2(100)NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	
	CONSTRAINT reply_fk FOREIGN KEY("REF")
	REFERENCES ROOTBOARD(SEQ)
);


CREATE TABLE FILEBOARD(
	F_SEQ NUMBER PRIMARY KEY,
	B_SEQ NUMBER,
	WRITER VARCHAR2(200) NOT NULL,
	ORIGIN_FNAME VARCHAR2(1000) NOT NULL,
	STORED_FNAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	F_REGDATE DATE DEFAULT SYSDATE,
	F_DELFLAG CHAR(1) NOT NULL,
	
	CONSTRAINT file_fk FOREIGN KEY(B_SEQ)
	REFERENCES ROOTBOARD(SEQ)
);

--게시글 상세 조회-
SELECT SEQ, ID, TITLE,CONTENT 
FROM ROOTBOARD r 

--새글 작성 테스트--
INSERT INTO ROOTBOARD (SEQ, ID, TITLE, CONTENT)
VALUES(NVL((SELECT MAX(SEQ)  FROM ROOTBOARD r),0)+1 ,'1234','1234','1234');

--답글 조회--
SELECT TITLE, REGDATE
	FROM (SELECT 'ㄴ'||TITLE AS TITLE, REGDATE, ROW_NUMBER() OVER(ORDER BY SYSDATE DESC) RN
	FROM REPLYBOARD r 
	WHERE REF='1')
	WHERE RN BETWEEN 1 AND 3;

--파일 업로드--
INSERT INTO FILEBOARD
	(F_SEQ, B_SEQ, WRITER, ORIGIN_FNAME, STORED_FNAME, FILE_SIZE, F_DELFLAG)
	VALUES(NVL((SELECT MAX(F_SEQ) FROM FILEBOARD r),0)+1,'1', 'MILK', '고라파덕.PNG', 'foilaskmdlasmdl', 146157, 'N');

SELECT ORIGIN_FNAME
	FROM FILEBOARD f 
	WHERE B_SEQ ='1'
	AND STORED_FNAME = 'foilaskmdlasmdl';

	SELECT COUNT(*)
			FROM REPLYBOARD;
			

















































