CREATE TABLE ANSWERBOARD(
SEQ NUMBER,
ID VARCHAR2(30) NOT NULL,
TITLE VARCHAR2(200) NOT NULL,
CONTENT VARCHAR2(1000),
REF NUMBER NOT NULL,
STEP NUMBER NOT NULL,
DEPTH NUMBER NOT NULL,
REGDATE DATE DEFAULT SYSDATE NOT NULL,
DELFLAG CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE ANSWERBOARD_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE ANSWERBOARD ADD CONSTRAINT ANSWERBOARD_PK PRIMARY KEY (SEQ);

CREATE TABLE USERINFO(
ID VARCHAR2(30) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
PASSWORD VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,HR.ANSWERBOARD
AUTH CHAR(1) NOT NULL,
DELFLAG CHAR(1) NOT NULL,
JOINDATE DATE NOT NULL
);

ALTER TABLE USERINFO ADD CONSTRAINT EMAIL_UK UNIQUE (EMAIL);
ALTER TABLE USERINFO ADD CONSTRAINT USERINFO_PK PRIMARY KEY (ID);



--전체글 조회
	SELECT SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", 
   CASE TO_CHAR(REGDATE, 'YYYY-MM-DD') WHEN TO_CHAR(SYSDATE, 'YYYY-MM-DD') THEN '오늘' ELSE TO_CHAR(REGDATE, 'YYYY-MM-DD') END AS REGDATE
   , DELFLAG
   FROM ANSWERBOARD
   ORDER BY "REF" DESC, STEP ASC;
--상세글 조회
	SELECT SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG
	FROM ANSWERBOARD
		WHERE SEQ ='7';
--답글 입력(insert)
	INSERT INTO ANSWERBOARD a (SEQ, ID, TITLE,
								CONTENT, REF, STEP,
								DEPTH)
			VALUES((SELECT NVL(MAX(SEQ),0) FROM ANSWERBOARD a5)+1,'A001','새로운 ROOT',
					'글 내용 작성', (SELECT REF FROM ANSWERBOARD a2 WHERE SEQ='8'),
					(SELECT STEP FROM ANSWERBOARD a3 WHERE SEQ = '8')+1,
					(SELECT DEPTH FROM ANSWERBOARD a4 WHERE SEQ='8')+1);
				
	INSERT INTO ANSWERBOARD a (SEQ, ID, TITLE,
							CONTENT, REF, STEP,
							DEPTH)
		VALUES((SELECT NVL(MAX(SEQ),0) FROM ANSWERBOARD a5)+1,'A001','새로운 답글 NEW',
				'글 내용 작성', (SELECT REF FROM ANSWERBOARD a2 WHERE SEQ='8'),
				(SELECT STEP FROM ANSWERBOARD a3 WHERE SEQ = '8')+1,
				(SELECT DEPTH FROM ANSWERBOARD a4 WHERE SEQ='8')+1);
--답글 입력(update)
	UPDATE ANSWERBOARD SET STEP = STEP+1
		WHERE REF = (SELECT REF FROM ANSWERBOARD a WHERE SEQ='6')
		AND STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ = '6');
--글 수정
	UPDATE ANSWERBOARD SET CONTENT = '내용을 수정합니다.'
		WHERE SEQ = '1';

--글 삭제
	UPDATE ANSWERBOARD SET DELFLAG ='Y'
		WHERE SEQ = '7';
--글 입력 (ROOT글 입력)
	INSERT INTO ANSWERBOARD a (SEQ, ID, TITLE,
								CONTENT, REF, STEP,
								DEPTH)
			VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A001','ROOT 글작성',
					'새글 작성 중',(SELECT NVL(MAX(REF),0) FROM ANSWERBOARD a2)+1,0,0);
				
	INSERT INTO ANSWERBOARD a (SEQ, ID, TITLE,
								CONTENT, REF, STEP,
								DEPTH)
			VALUES((SELECT NVL(MAX(SEQ),0) FROM ANSWERBOARD a)+1, 'A001','ROOT 글작성',
					'새글 작성 중',(SELECT NVL(MAX(REF),0) FROM ANSWERBOARD a2)+1,0,0);
--진짜 삭제
	DELETE FROM ANSWERBOARD a WHERE SEQ = '9';
--다중 삭제
	UPDATE ANSWERBOARD SET DELFLAG ='Y'
		WHERE SEQ = '8';
--다중 삭제
	UPDATE ANSWERBOARD SET DELFLAG ='Y'
		WHERE SEQ IN ('8','10','9');

--시나리오 테스트
--답글 작성
SELECT SEQ, ID, LPAD(' ',DEPTH*10)||TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG
	FROM ANSWERBOARD
		ORDER BY REF DESC, STEP ASC;	

SELECT SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG
	FROM ANSWERBOARD
		WHERE SEQ ='4';	

	
UPDATE ANSWERBOARD SET STEP = STEP+1
	WHERE REF = (SELECT REF FROM ANSWERBOARD a WHERE SEQ='4')
	AND STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ = '4');

INSERT INTO ANSWERBOARD a (SEQ, ID, TITLE,
							CONTENT, REF, STEP,
							DEPTH)
		VALUES((SELECT NVL(MAX(SEQ),0) FROM ANSWERBOARD a5)+1,'A999','REPLAY INSERT',
				'REPLAY INSERT', (SELECT REF FROM ANSWERBOARD a2 WHERE SEQ='4'),
				(SELECT STEP FROM ANSWERBOARD a3 WHERE SEQ = '4')+1,
				(SELECT DEPTH FROM ANSWERBOARD a4 WHERE SEQ='4')+1);
	
	
	
	
	
	
--회원등록

INSERT INTO USERINFO
(ID, NAME, PASSWORD, EMAIL, AUTH, DELFLAG, JOINDATE)
VALUES('user', '사용자', '1234', 'user@user.com', 'U', 'N', sysdate);

INSERT INTO USERINFO
(ID, NAME, PASSWORD, EMAIL, AUTH, DELFLAG, JOINDATE)
VALUES('admin', '관리자', '1234', 'admin@admin.com', 'A', 'N', sysdate);

INSERT INTO USERINFO
(ID, NAME, PASSWORD, EMAIL, AUTH, DELFLAG, JOINDATE)
VALUES('hello', 'hello', '1234', 'hello@hello.com', 'U', 'N', sysdate);

SELECT ID,NAME,EMAIL, AUTH
	FROM USERINFO
		WHERE ID='user'
		AND PASSWORD='1234';
	













