/*
1:n의 관계에서 mybatis & 객체
	1) 쿼리에서 LEFT Join을 통해서 작업
	2) 쿼리결과와 객체가 담겨 있는 형태가 다르다
	3) 조회의 실행 selectList -> List
				selectOne->OBJECT
				selectMap -> Map
				selectCursor -> Map
*/

-- 하나의 root 글에 DEPTH 1인 답글을 작성 할 수 있다.
-- 장점 : ROOT글이 사라지면 답글을 전혀 볼 수 없게 만들거나 삭제 할 수 있다.
-- 단점 : 쿼리작성(1:N), 답글의 답글을 작성 할 수 없다.

CREATE TABLE ROOTBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE TABLE REPLYBOARD(
	SEQ CHAR(3) PRIMARY KEY,
	REF NUMBER,
	TITLE VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL
);

ALTER TABLE REPLYBOARD ADD CONSTRAINT REPLAYBOARD_FK FOREIGN KEY (REF) REFERENCES ROOTBOARD(SEQ);


INSERT INTO ROOTBOARD
	(SEQ, ID, TITLE, CONTENT, REGDATE)
		VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM ROOTBOARD r), 'D01', 'ROOT 글 작성', '부모의 컨텐츠에 내용 글', SYSDATE);
	
SELECT LPAD(1,3,0) 
	FROM DUAL;

SELECT 'R'||LPAD(1,3,'0')FROM DUAL;

SELECT SUBSTR('R001',2) FROM DUAL;

SELECT NVL(MAX(SUBSTR('R001',2)),0)+1 FROM DUAL;

INSERT INTO REPLYBOARD
	(SEQ, "REF", TITLE, REGDATE)
	VALUES('R'||LPAD((SELECT NVL(MAX(SUBSTR(SEQ,2)),0)+1 FROM REPLYBOARD r),2,'0')
		, 1, '답글 3이 작성 됩니다', SYSDATE);

SELECT r.SEQ,r.TITLE ,r.CONTENT, r.REGDATE,
		r2.SEQ ,r2.TITLE ,r2.REGDATE
	FROM ROOTBOARD r  LEFT JOIN REPLYBOARD r2 
	ON r.SEQ =r2."REF" ; 


