-- ANSWERBOARD와 연결되는 File 테이블
CREATE TABLE FILEBOARD(
	F_SEQ NUMBER PRIMARY KEY,
	B_SEQ NUMBER NOT NULL,
	WRITER VARCHAR2(200),
	ORIGIN_FNAME VARCHAR2(1000) NOT NULL,-- 원본 파일
	STORED_FNAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	FILE_REGDATE DATE NOT NULL,
	F_DELFLAG CHAR(1) NOT NULL
	);

CREATE SEQUENCE FILE_SEQ START WITH 1 INCREMENT BY 1;


SELECT SEQ,ID ,CONTENT ,REGDATE , ORIGIN_FNAME 
	FROM ANSWERBOARD a LEFT JOIN FILEBOARD f 
	ON a.SEQ =f.B_SEQ 
	WHERE  SEQ='190';

SELECT SEQ,ID,TITLE ,CONTENT ,REGDATE 
	FROM (
		SELECT SEQ,ID, TITLE , CONTENT , REGDATE,
			ROW_NUMBER ()OVER (ORDER BY "REF" DESC, STEP ASC) RN
		FROM ANSWERBOARD a 
	)
	WHERE RN<11;

SELECT a.SEQ ,a.ID ,a.CONTENT ,a.REGDATE ,f.ORIGIN_FNAME 
	FROM ANSWERBOARD a LEFT JOIN FILEBOARD f 
	ON a.SEQ = f.B_SEQ ;
	
INSERT INTO FILEBOARD
	(F_SEQ, B_SEQ, WRITER, ORIGIN_FNAME, STORED_FNAME, FILE_SIZE, FILE_REGDATE, F_DELFLAG)
	VALUES(FILE_SEQ.NEXTVAL, '52', 'MILK', '고라파덕.PNG', 'foilaskmdlasmdl', 146157, SYSDATE, 'N');

SELECT *
	FROM FILEBOARD f 
		WHERE ORIGIN_FNAME = '고라파덕.PNG';

SELECT SEQ, ID, TITLE||'('||COUNT||')' , REGDATE
	FROM (
		SELECT SEQ,ID,TITLE, REGDATE, (SELECT COUNT(*)
										FROM FILEBOARD f
										WHERE a.SEQ = f.B_SEQ) AS COUNT,
										ROW_NUMBER () OVER (ORDER BY REF DESC, STEP ASC)AS RN
		FROM ANSWERBOARD a 
	)
	WHERE RN<11 OR SEQ='190';
	