-- JOBS 테이블 복사

CREATE TABLE JOB AS SELECT * FROM JOBS j ;

SELECT JOB_ID , JOB_TITLE , MIN_SALARY ,MAX_SALARY 
	FROM JOB ;
	
--SELECT01
--job_id 입력 max_salary 출력

SELECT MAX_SALARY 
	FROM JOB j
	WHERE JOB_ID = 'AD_PRES';

--SELECT02
--JOB_ID 입력 받고 전체 컬럼의 값을 출력

SELECT*
	FROM JOB j
		WHERE JOB_ID = 'AD_PRES';
--SELECT 03
	SELECT FIRST_NAME , LAST_NAME , EMPLOYEE_ID , SALARY 
		FROM EMPLOYEES e 
			WHERE EMPLOYEE_ID ='113';
			
--SELECT05
	SELECT JOB_ID ,JOB_TITLE ,MIN_SALARY ,MAX_SALARY 
	FROM JOB j
		WHERE JOB_ID = 'AD_PRES'
			AND JOB_TITLE = 'President';
CREATE TABLE PLAYER AS SELECT PLAYER_ID, PLAYER_NAME, BACK_NO,TEAM_ID
	FROM SQLD.PLAYER
	
DROP TABLE PLAYER;

SELECT PLAYER_NAME ||'('||BACK_NO||')' AS ID,
	TEAM_ID TITLE
	FROM PLAYER
		WHERE PLAYER_ID='2012001';
	
SELECT JOB_ID ,JOB_TITLE ,MIN_SALARY ,MAX_SALARY
	FROM JOB
		WHERE MIN_SALARY <3000;

INSERT INTO JOB (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
	VALUES('IT','Programmer',1000,3000)
	
DELETE FROM JOB
	WHERE JOB_ID = 'IT';
COMMIT;

SELECT *
	FROM JOB j ;

UPDATE JOB
	SET JOB_TITLE='Developer'
		WHERE JOB_ID = 'IT_PROG';

	