SELECT COUNT(*),TEAM_ID 
	FROM PLAYER p 
	WHERE NATION IS NOT NULL
	GROUP BY TEAM_ID
	ORDER BY TEAM_ID;

--KLMS01006	선수를 영입 했을 때 그 선수가 외국인일 경우 팀별 외국인 보유 횟수 증가하는 기능
--K리그 규정 상 외국인 용병은 5명을 초과 할 수 없기 때문에 이 부분은 service로 처리 할 계획

--플레이어 추가시
CREATE OR REPLACE TRIGGER FPLAYER_ADD
	AFTER INSERT ON PLAYER
	FOR EACH ROW 
BEGIN
	IF :NEW.NATION IS NOT NULL 
	
	THEN
		UPDATE TEAM SET FOREIGNER_COUNT = FOREIGNER_COUNT+1;
	END IF;
END;

--플레이어 삭제시
CREATE OR REPLACE TRIGGER FPLAYER_DEL
	AFTER DELETE ON PLAYER
	FOR EACH ROW 
BEGIN 
	IF :NEW.NATION IS NOT NULL 
	THEN 
		UPDATE TEAM SET FOREIGNER_COUNT = FOREIGNER_COUNT-1
			WHERE TEAM_ID = :NEW.TEAM_ID;
	END IF;
END;


--KLMS01007	선수 영입시 K리그 규정에 의거하여 국적이 북한이거나  제일 교포는 내국인으로 분류하는 기능
	
CREATE OR REPLACE TRIGGER BPLAYER_ADD
BEFORE INSERT ON PLAYER
FOR EACH ROW
BEGIN
    IF 
	    :NEW.NATION = '북한' OR :NEW.NATION = '제일'
	    
    THEN
        :NEW.NATION := '';
    END IF;
END;

SELECT *
	FROM PLAYER p 
		WHERE PLAYER_NAME  = '임정운';
	
INSERT INTO PLAYER p (PLAYER_ID,PLAYER_NAME,TEAM_ID,NATION)
	VALUES('123456','임정운','K00','제일');	

UPDATE PLAYER  SET NATION =''
	WHERE NATION = '북한';

DELETE FROM PLAYER p 
		WHERE PLAYER_NAME ='임정운'
--KLMS02001	팀을 삭제하는 기능
		
	UPDATE PLAYER SET TEAM_ID = 'K00' 
		WHERE TEAM_ID = 'K03';
	DELETE FROM TEAM 
		WHERE TEAM_ID = 'K03';
	
--KLMS03001	경기 일정을 추가하는 기능
	INSERT INTO SCHEDULE s (STADIUM_ID,SCHE_DATE,GUBUN,HOMETEAM_ID,AWAYTEAM_ID)
		VALUES('C02',SYSDATE,'N','K03','K09');
	
--KLMS03002	경기 일정을 수정하는 기능
	UPDATE SCHEDULE SET SCHE_DATE = SYSDATE +1
		WHERE SCHE_DATE='23/06/17'
		AND GUBUN ='N';